### PR TITLE
Export also LC_TIME in case babel checks it first to determine the lo…

### PR DESCRIPTION
**Pull request by carolinux**
…cale (#34)

### CODE REVIEW

**Comment by plumdog** [comment]
I think I'd rather the environment-variable setting happened in `tests/__init__.py` so that you don't have to set them yourself if your local machine is not set to have the locale the tests expect.

However, I think that what you've found has flushed out something in Babel that makes me a bit sad. In particular, [this line](https://github.com/python-babel/babel/blob/903898f97d1010f5bf39b6b6d7e153fc6c2cc15b/babel/dates.py#L33) - specifically that it happens at import time. I suppose it isn't that horrible, as you wouldn't normally expect LC_TIME to change during a program's execution, perhaps. Though Bable prefers LC_TIME over LC_ALL, which appears to violate the suggestion made by https://help.ubuntu.com/community/Locale which says
> LC_ALL - Overrides individual LC_* settings: if LC_ALL is set, none of the below have any effect.

(I know that Ubuntu is not the authority on this, but I couldn't find anything that was.)

So the fix for this seems to be to move the existing setting of environment variable to just before
```python
from flask_table import ...
```
in `tests/__init__.py`, and add `LC_TIME` to the list that are set to be `''`. I'd be interested to know if something along those lines fixes the problem you originally found.

**Comment by plumdog** [comment]
Also: may need to manually set `LC_ALL` to `'en_GB.UTF-8'` rather than to `''` to make that work.

**Comment by carolinux** [comment]
ok, I can try that.

**Comment by plumdog** [comment]
Fixed by #46. Closing.

**Pull request closed without merging**
