### PR TITLE
LinkCol can use not only item params creating url

### PR DESCRIPTION
**Pull request by diego-vasarelli**
Sometimes could be useful to use params not in the item to create the link.
With this modify the LinkCol can manage also this extra params.

### CODE REVIEW

**Comment by plumdog** [comment]
I totally agree with the idea, but I don't like that it breaks the recursive nature of the lookups.

In particular, [this test](https://github.com/plumdog/flask_table/blob/master/tests/__init__.py#L443) should still pass, where it is not getting a url kwarg from the item directly, but from a related item using `_recursive_getattr`. By doing the `hasattr` check, this will break.

I would instead suggest that we add an optional `url_kwargs_extras` argument for `LinkCol` that is a dict. This should have keys that are the parameters for the url and values that should be added. We would then merge these dicts before passing them to `url_for`.

By keeping these two dicts separate, we don't have to do any guessing/assuming about what the strings actually mean. And we're being explicit rather than implicit, so we score more Python-Zen points too.

**Comment by diego-vasarelli** [comment]
Ok, I think I got it.

This is a preview of what I've done to use this new dict

```python
class LinkCol(Col):
    """Format the content as a link. Requires a endpoint to use to find
    the url and can also take a dict of url_kwargs which is expected
    to have values that are strings which are used to get data from
    the item.

    Eg:

    view = LinkCol('View', 'view_fn', url_kwargs=dict(id='id'))

    This will create a link to the address given by url_for('view_fn',
    id=item.id) for each item in the iterable.
    
    The dict url_kwargs_extra can be used to specify other link param 
    not in the item.

    Eg:

    view = LinkCol('View', 'view_fn', url_kwargs=dict(id='id'),
                                      url_kwargs_extra=dict(foo='bar'))

    This will create a link to the address given by url_for('view_fn',
    id=item.id, foo='bar') for each item in the iterable.

    """
    def __init__(self, name, endpoint, attr=None, attr_list=None,
                 url_kwargs=None, url_kwargs_extras=None, **kwargs):
        Col.__init__(self, name, attr=attr, attr_list=attr_list, **kwargs)
        self.endpoint = endpoint
        if url_kwargs is None:
            self._url_kwargs = {}
        else:
            self._url_kwargs = url_kwargs

        if url_kwargs_extras is None:
            self._url_kwargs_extras = {}
        else:
            self._url_kwargs_extras = url_kwargs_extras

    def url_kwargs(self, item):

        item_args = {k: _recursive_getattr(item, v)
                for k, v in self._url_kwargs.items()}

        extra_args = {k: v for k, v in self._url_kwargs_extras.items()}

        extra_args.update(item_args)
        
        return extra_args

    def get_attr_list(self, attr):
        return Col.get_attr_list(self, None)

    def text(self, item, attr_list):
        if attr_list:
            return self.from_attr_list(item, attr_list)
        else:
            return self.name

    def url(self, item):
        return url_for(self.endpoint, **self.url_kwargs(item))

    def td_contents(self, item, attr_list):
        return '<a href="{url}">{text}</a>'.format(
            url=self.url(item),
            text=self.td_format(self.text(item, attr_list)))
```

If you think It's ok I'll proceed with the merge request.

**Comment by plumdog** [comment]
Looks excellent to me!

You can simplify the `url_kwargs` method a bit though I think:
```python
def url_kwargs(self, item):
    # Get the arguments from the item
    args = {k: _recursive_getattr(item, v)
            for k, v in self._url_kwargs.items()}
    # Combine with the extras
    args.update(self._url_kwargs_extras)
    return args
```
Though this does highlight the question about what should happen if there's a key that appears in both. My example gives preference to the extras, while yours gives preference to the values from the item.
Eg
```python
view = LinkCol('View', 'view_fn', url_kwargs=dict(id='id'), url_kwargs_extra=dict(id='custom'))
```
Should this end up calling `url_for('view_fn', id=item.id)` or `url_for('view_fn', id='custom')`?
I think I'm happy with either, really. But whichever we choose we should make sure it is documented.

**Comment by diego-vasarelli** [comment]
I had the same problem and I chose to give preference to the item.

In my case my url are build on three or more parameters, first two are used to specify which output and the main script, the third is used to specify the action.
The parameters starting from the forth are optional (= items attributes).

In a situation like this (but in general, I think) extras parameters should no overlaps with item parameters, and if it happens item parameters should replace the extra one.
If extra parameters overrides item parameters so we can say that there is no need to use item at all and we can use only `url_kwargs_extra` dict without `url_kwargs`.

I'm agree to produce documentation, I had some difficult to find an example for the LinkCol and I had to read the code to well understand the point.

**Comment by jonathanunderwood** [comment]
Any progress on this one? Would be great to merge this really useful functionality.

**Comment by jonathanunderwood** [comment]
FWIW I would favour the design where item parameters override the extra parameters if both are given, as advocated by @diego-vasarelli - that seems the most flexible and useful design to me.

**Comment by plumdog** [comment]
Covered by #50. Closing.

**Pull request closed without merging**
