### PR TITLE
Call to td_format for LinkCol td_contents.

### PR DESCRIPTION
**Pull request by nicjhan**

### CODE REVIEW

**Comment by plumdog** [comment]
Totally agree. Thanks for the PR!

**Comment by plumdog** [comment]
0.2.10 is now on PyPI - https://pypi.python.org/pypi/Flask-Table/0.2.10

**Comment by ravitejachebrolu** [comment]
can we make the FLASK-TABLE scrollable? I tried doing it with CSS , but it doesn't appear to be working.

**Comment by plumdog** [comment]
Hi @ravitejachebrolu - could you open a new issue for your question? It sounds like it might be separate to this PR.

**Comment by ravitejachebrolu** [comment]
@plumdog  i got it cleared. no worries. from next i shall open a new issue. thanks and sorry for the trouble

**Pull request merged**
